<robot name="pf1s1" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="camera_length" value="0.005" /> 
    <xacro:property name="camera_width" value="0.06" /> 
    <xacro:property name="camera_height" value="0.01" /> 
    <xacro:property name="joint_camera_x" value="${base_link_length / 2 + 0.01}" />
    <xacro:property name="joint_camera_y" value="0" />
    <xacro:property name="joint_camera_z" value="0" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black">
                <color rgba="0 0 0 0.8" />
            </material>
        </visual>
    </link>

    <joint name="camera2base" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0 0 0" />
    </joint>

</robot>